(()=>{
'use strict';if(window.__deliveryArchiveInstalled)return;window.__deliveryArchiveInstalled=true;
const FN='https://vnnvuxccazkdzwqjmntz.supabase.co/functions/v1/delivery-note-archive',AI='https://vnnvuxccazkdzwqjmntz.supabase.co/functions/v1/delivery-note-ai',POS='https://vnnvuxccazkdzwqjmntz.supabase.co/functions/v1/delivery-note-position-sync',PLAN='https://vnnvuxccazkdzwqjmntz.supabase.co/functions/v1/delivery-note-retry-plan',CONCURRENCY=2;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function post(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
function niceName(path){return String(path||'').split('/').pop()?.replace(/^\d{13}-[a-z0-9]+-/i,'')||path}
async function openPath(path,b){b.disabled=true;try{b.textContent='開いています…';const j=await post(FN,{action:'url',path});window.open(j.url,'_blank','noopener')}catch(e){alert('納品書を開けませんでした：'+e.message)}finally{b.disabled=false;b.textContent='原本を見る'}}
async function downloadPath(path,name,b){b.disabled=true;try{b.textContent='準備中…';const j=await post(FN,{action:'download',path,file_name:name});const a=document.createElement('a');a.href=j.url;a.download=name||niceName(path);document.body.appendChild(a);a.click();a.remove()}catch(e){alert('ダウンロードできませんでした：'+e.message)}finally{b.disabled=false;b.textContent='ダウンロード'}}
function fmtSec(sec){sec=Math.max(0,Math.round(sec));const m=Math.floor(sec/60),s=sec%60;return m?`${m}分${String(s).padStart(2,'0')}秒`:`${s}秒`}
async function persist(path,pageItems){if(!pageItems?.length)return 0;let pos=0;try{const s=await post(POS,{path,items:pageItems});pos=Number(s.updated||0)}catch(e){console.warn(e)}try{const s=await post(AI,{action:'sync_reanalysis',path,items:pageItems});pos=Math.max(pos,Number(s.positions_updated||0))}catch(e){console.warn(e)}return pos}
async function reanalyze(path,name,b){if(!confirm('原本位置がまだ記録されていないページだけをAIで再読み取りします。\n成功済みページは読み直しません。よろしいですか？'))return;b.disabled=true;const old=b.textContent,started=Date.now();try{b.textContent='未処理ページ確認中…';const plan=await post(PLAN,{action:'plan',path}),done=new Set((plan.recorded_pages||[]).map(Number));b.textContent='PDFを準備中…';const prep=await post(AI,{action:'prepare_reanalysis',path,file_name:name}),all=prep.chunks||[],targets=all.filter(x=>!done.has(Number(x.source_page))),skipped=all.filter(x=>done.has(Number(x.source_page)));if(skipped.length)post(PLAN,{action:'cleanup',paths:skipped.map(x=>x.chunk_path)}).catch(console.warn);if(!targets.length){alert(`再読み取り不要です。\n${all.length}ページすべて原本位置が記録済みです。`);return}const items=[],fails=[];let completed=0,pos=0,next=0;const progress=()=>{const elapsed=(Date.now()-started)/1000,avg=completed?elapsed/completed:0,remain=completed?avg*(targets.length-completed)/CONCURRENCY:0;b.textContent=`未処理AI ${completed}/${targets.length}${completed?` 残り約${fmtSec(remain)}`:''}`};async function worker(){while(true){const i=next++;if(i>=targets.length)return;const t=targets[i];try{const r=await post(AI,{action:'analyze_storage',...t}),pageItems=r.items||[];items.push(...pageItems);if(r.failed_pages?.length)fails.push(...r.failed_pages);if(pageItems.length)pos+=await persist(path,pageItems)}catch(e){fails.push({page:t.source_page,error:e.message})}finally{completed++;progress()}}}progress();await Promise.all(Array.from({length:Math.min(CONCURRENCY,targets.length)},()=>worker()));alert(`未処理ページ再読み取り完了\n2ページ並行で処理しました。\n対象 ${targets.length}ページ（成功済み ${skipped.length}ページはスキップ）\n成功 ${targets.length-fails.length}ページ / 失敗 ${fails.length}ページ\n明細 ${items.length}件\n原本位置を ${pos}件 記録しました。`);window.dispatchEvent(new CustomEvent('delivery-archive-reanalyzed',{detail:{path,items,failed_pages:fails,positions_updated:pos}}))}catch(e){alert('AI再読み取りに失敗しました：'+e.message)}finally{b.disabled=false;b.textContent=old}}
let timer=null,lastSuppliers=[];
function ensure(){const tabs=document.querySelector('.material-tabs');if(!tabs)return null;let tab=tabs.querySelector('[data-tab="archive"]');if(!tab){tab=document.createElement('button');tab.className='material-tab';tab.dataset.tab='archive';tab.textContent='原本保管庫';tabs.querySelector('[data-tab="delivery"]')?.insertAdjacentElement('afterend',tab)}let panel=document.getElementById('mp-archive');if(!panel){panel=document.createElement('section');panel.className='material-panel';panel.id='mp-archive';panel.style.display='none';document.getElementById('materialApp')?.appendChild(panel)}return{tab,panel}}
function opts(s,a,c){s.innerHTML='<option value="">すべてのサプライヤー</option>'+a.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(c&&a.includes(c))s.value=c}
async function load(q='',supplier=''){const list=document.getElementById('deliveryArchiveList');if(!list)return;list.innerHTML='検索中…';try{const j=await post(FN,{action:'list',q,supplier}),items=j.items||[],sel=document.getElementById('deliveryArchiveSupplier');lastSuppliers=j.suppliers||lastSuppliers;opts(sel,lastSuppliers,supplier);if(!items.length){list.innerHTML='<div class="empty-state">該当する納品書原本はありません</div>';return}list.innerHTML=items.map(x=>{const name=niceName(x.path),m=(x.materials||[]).slice(0,5),s=x.suppliers||[];return`<div style="padding:14px 0;border-bottom:1px solid #e5e7eb"><div style="font-weight:900">${esc(name)}</div>${s.length?`<div style="font-size:13px;font-weight:800;margin-top:4px">仕入先：${esc(s.join(' / '))}</div>`:''}${m.length?`<div style="font-size:12px;color:#4b5563;margin-top:3px">材料：${esc(m.join('、'))}</div>`:''}<div style="display:flex;gap:7px;flex-wrap:wrap;margin-top:9px"><button data-act="open" data-path="${esc(x.path)}">原本を見る</button><button data-act="download" data-path="${esc(x.path)}" data-name="${esc(name)}">ダウンロード</button><button data-act="ai" data-path="${esc(x.path)}" data-name="${esc(name)}" style="background:#111827;color:white">失敗・未記録ページだけ再読取</button></div></div>`}).join('');list.querySelectorAll('button').forEach(b=>{b.style.cssText+=';border:1px solid #2563eb;border-radius:9px;padding:9px 11px;font-weight:800';const a=b.dataset.act;if(a==='open')b.onclick=()=>openPath(b.dataset.path,b);if(a==='download')b.onclick=()=>downloadPath(b.dataset.path,b.dataset.name,b);if(a==='ai')b.onclick=()=>reanalyze(b.dataset.path,b.dataset.name,b)})}catch(e){list.innerHTML='<div style="color:#b91c1c">原本一覧の読み込みに失敗しました：'+esc(e.message)+'</div>'}}
function filters(){return{q:(document.getElementById('deliveryArchiveSearch')?.value||'').trim(),supplier:document.getElementById('deliveryArchiveSupplier')?.value||''}}
function render(){const z=ensure();if(!z)return;z.panel.innerHTML='<div class="card"><div class="card-title">納品書 原本保管庫</div><div class="material-note">原本を見る・PDFをダウンロードできます。AI再読み取りは、原本位置が記録済みの成功ページを自動で飛ばし、失敗・未記録ページだけ処理します。</div><div class="field" style="margin-top:12px"><label>サプライヤー</label><select id="deliveryArchiveSupplier"><option value="">すべてのサプライヤー</option></select></div><div class="field"><label>原本を検索</label><input id="deliveryArchiveSearch" placeholder="材料名・単価・日付・ファイル名"></div><div id="deliveryArchiveList">読み込み中…</div></div>';const i=document.getElementById('deliveryArchiveSearch'),s=document.getElementById('deliveryArchiveSupplier');i.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{const f=filters();load(f.q,f.supplier)},250)};s.onchange=()=>{const f=filters();load(f.q,f.supplier)};load()}
function show(){const z=ensure();if(!z)return;document.querySelectorAll('.material-tab').forEach(x=>x.classList.toggle('active',x===z.tab));document.querySelectorAll('.material-panel').forEach(x=>{const on=x===z.panel;x.classList.toggle('active',on);x.style.display=on?'block':'none'});render()}
function hook(){const z=ensure();if(z&&!z.tab.dataset.h){z.tab.dataset.h='1';z.tab.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();show()},true)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(hook,300));else setTimeout(hook,300);
})();