(()=>{
'use strict';
if(window.__deliveryArchiveInstalled)return;window.__deliveryArchiveInstalled=true;
const FN='https://vnnvuxccazkdzwqjmntz.supabase.co/functions/v1/delivery-note-archive';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
async function post(body){const r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
function niceName(path){return String(path||'').split('/').pop()?.replace(/^\d{13}-[a-z0-9]+-/i,'')||path}
async function openPath(path,btn){btn.disabled=true;btn.textContent='開いています…';try{const j=await post({action:'url',path});window.open(j.url,'_blank','noopener')}catch(e){alert('納品書を開けませんでした：'+e.message)}finally{btn.disabled=false;btn.textContent='原本を見る'}}
let timer=null;
async function load(q=''){const list=document.getElementById('deliveryArchiveList');if(!list)return;list.innerHTML='検索中…';try{const j=await post({action:'list',q});const items=j.items||[],cleaned=Number(j.cleaned||0);let note=cleaned>0?`<div style="margin:8px 0;padding:9px 10px;border-radius:9px;background:#ecfdf5;color:#166534;font-size:12px;font-weight:800">重複・期限切れの原本を ${cleaned}件 整理しました。</div>`:'';if(!items.length){list.innerHTML=note+'<div class="empty-state">該当する納品書原本はありません</div>';return}list.innerHTML=note+items.map(x=>{const mats=(x.materials||[]).slice(0,5),sups=(x.suppliers||[]);return `<div style="padding:12px 0;border-bottom:1px solid #e5e7eb"><div style="font-weight:900">${esc(niceName(x.path))}</div>${sups.length?`<div style="font-size:13px;font-weight:800;margin-top:4px">仕入先：${esc(sups.join(' / '))}</div>`:''}${mats.length?`<div style="font-size:12px;color:#4b5563;margin-top:3px;line-height:1.5">材料：${esc(mats.join('、'))}${(x.materials||[]).length>5?' ほか':''}</div>`:''}<div style="font-size:12px;color:#6b7280;margin:3px 0">保存：${esc(String(x.created_at||'').replace('T',' ').slice(0,19))}</div><button type="button" data-path="${esc(x.path)}" style="border:1px solid #2563eb;background:#eff6ff;color:#1d4ed8;border-radius:9px;padding:8px 12px;font-weight:800">原本を見る</button></div>`}).join('');list.querySelectorAll('button[data-path]').forEach(b=>b.onclick=()=>openPath(b.dataset.path,b))}catch(e){list.innerHTML='<div style="color:#b91c1c">原本一覧の読み込みに失敗しました：'+esc(e.message)+'</div>'}}
async function render(){const panel=document.getElementById('mp-delivery');if(!panel)return;let box=document.getElementById('deliveryArchiveBox');if(box)box.remove();box=document.createElement('div');box.id='deliveryArchiveBox';box.className='card';box.style.marginTop='12px';box.innerHTML='<div class="card-title">保存済みの納品書原本</div><div class="material-note">AIが読み取った元PDF・画像を90日間保存します。仕入先・材料名・単価・日付で検索できます。</div><div class="field" style="margin-top:12px"><label>原本を検索</label><input id="deliveryArchiveSearch" placeholder="例：緑川化成、シール、1,220、2026-08-21" style="font-size:16px"></div><div id="deliveryArchiveList" style="margin-top:10px">読み込み中…</div>';panel.appendChild(box);const input=box.querySelector('#deliveryArchiveSearch');input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>load(input.value.trim()),250)});load('')}
function hook(){const tab=document.querySelector('.material-tab[data-tab="delivery"]');if(tab&&!tab.dataset.archiveHook){tab.dataset.archiveHook='1';tab.addEventListener('click',()=>setTimeout(render,50))}if(document.getElementById('mp-delivery')?.classList.contains('active'))render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{setTimeout(hook,700);setTimeout(hook,1800)},{once:true});else{setTimeout(hook,700);setTimeout(hook,1800)}
})();