(()=>{
'use strict';
if(window.__duplicateMaterialReview)return;window.__duplicateMaterialReview=true;
const MERGE_FN='https://vnnvuxccazkdzwqjmntz.supabase.co/functions/v1/material-merge';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[\s　・･_\-()（）]/g,'').replace(/[×x*]/g,'×');
const num=v=>v==null||v===''?null:Number(v);
function levenshtein(a,b){a=norm(a);b=norm(b);if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;let prev=Array.from({length:b.length+1},(_,i)=>i),cur=[];for(let i=1;i<=a.length;i++){cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=cur}return prev[b.length]}
function nameSimilarity(a,b){const aa=norm(a),bb=norm(b);const d=levenshtein(aa,bb),max=Math.max(aa.length,bb.length,1);return 1-d/max}
function sameSpec(a,b){return norm(a.spec)===norm(b.spec)}
function sameSupplier(a,b){return norm(a.supplier)===norm(b.supplier)}
function thicknessClose(a,b){const x=num(a.thickness_mm),y=num(b.thickness_mm);return x==null&&y==null||x!=null&&y!=null&&Math.abs(x-y)<0.0001}
function pairKey(a,b){return [Math.min(Number(a.id),Number(b.id)),Math.max(Number(a.id),Number(b.id))].join(':')}
function ignored(){try{return new Set(JSON.parse(localStorage.getItem('ignoredMaterialDuplicatePairs')||'[]'))}catch{return new Set()}}
function saveIgnored(set){localStorage.setItem('ignoredMaterialDuplicatePairs',JSON.stringify([...set]))}
async function loadData(){const [m,p]=await Promise.all([supabaseClient.from('materials').select('*').eq('active',true).order('name'),supabaseClient.from('material_prices').select('material_id,price,effective_from,id').order('effective_from',{ascending:false}).order('id',{ascending:false})]);if(m.error)throw m.error;if(p.error)throw p.error;const latest=new Map();for(const x of p.data||[]){const k=String(x.material_id);if(!latest.has(k))latest.set(k,x)}return (m.data||[]).map(x=>({...x,__price:latest.get(String(x.id))||null}))}
function candidatePairs(rows){const out=[],skip=ignored();for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const a=rows[i],b=rows[j],key=pairKey(a,b);if(skip.has(key)||!sameSupplier(a,b)||!thicknessClose(a,b))continue;const ns=nameSimilarity(a.name,b.name),spec=sameSpec(a,b),pa=num(a.__price?.price),pb=num(b.__price?.price),priceSame=pa!=null&&pb!=null&&Math.abs(pa-pb)<0.001;let score=0;if(spec)score+=3;if(priceSame)score+=2;if(ns>=.93)score+=4;else if(ns>=.84)score+=3;else if(ns>=.72)score+=2;const specA=norm(a.spec),specB=norm(b.spec);if(specA&&specB&&(specA.includes(specB)||specB.includes(specA)))score+=1;if(score>=6)out.push({a,b,score,ns,priceSame})}return out.sort((x,y)=>y.score-x.score||y.ns-x.ns)}
function ensureBanner(){let x=document.getElementById('duplicateReviewBanner');if(x)return x;x=document.createElement('div');x.id='duplicateReviewBanner';x.style.cssText='display:none;margin:0 0 14px;padding:14px;border:2px solid #f59e0b;border-radius:14px;background:#fff7ed;color:#7c2d12;font-weight:900';const card=document.querySelector('#mp-list .card');if(card)card.insertBefore(x,card.firstChild);return x}
function money(p){return p?.price!=null?Number(p.price).toLocaleString('ja-JP')+'円':'未登録'}
function detail(m,label,color){return `<div style="border:2px solid ${color};border-radius:13px;padding:12px;margin-top:10px"><div style="font-size:12px;font-weight:800;color:${color}">${label}</div><div style="font-size:18px;font-weight:900;margin-top:3px">${esc(m.name)}</div><div style="font-size:13px;line-height:1.6;margin-top:5px">規格：${esc(m.spec||'未設定')}<br>厚み：${esc(m.thickness_mm??'未設定')} mm<br>仕入先：${esc(m.supplier||'未設定')}<br>最新単価：${esc(money(m.__price))}${m.__price?.effective_from?' ('+esc(m.__price.effective_from)+')':''}</div></div>`}
function ask(pair){return new Promise(resolve=>{document.getElementById('duplicateReviewModal')?.remove();let keep=pair.b,remove=pair.a;const wrap=document.createElement('div');wrap.id='duplicateReviewModal';wrap.style.cssText='position:fixed;inset:0;z-index:2147483647;background:rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center;padding:18px;box-sizing:border-box';const draw=()=>{wrap.innerHTML=`<div style="width:min(540px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:20px;padding:20px;color:#111827"><div style="font-size:22px;font-weight:900">これは同じ材料ですか？</div><div style="font-size:13px;color:#6b7280;margin-top:5px">同じなら、下の「残す材料」に単価履歴・入出庫履歴をまとめます。</div>${detail(remove,'統合して消す候補','#dc2626')}${detail(keep,'残す材料','#15803d')}<button data-a="swap" style="width:100%;margin-top:10px;padding:11px;border:1px solid #64748b;border-radius:10px;background:#fff;font-weight:800">↑↓ 残す材料を入れ替える</button><button data-a="merge" style="width:100%;margin-top:9px;padding:14px;border:0;border-radius:11px;background:#15803d;color:#fff;font-size:16px;font-weight:900">同じ材料 → 1件に統合</button><button data-a="different" style="width:100%;margin-top:9px;padding:13px;border:2px solid #2563eb;border-radius:11px;background:#fff;color:#1d4ed8;font-weight:900">別の材料 → 今後この組み合わせは聞かない</button><button data-a="later" style="width:100%;margin-top:9px;padding:12px;border:0;border-radius:11px;background:#e5e7eb;font-weight:800">あとで確認</button></div>`;wrap.querySelector('[data-a="swap"]').onclick=()=>{[keep,remove]=[remove,keep];draw()};wrap.querySelector('[data-a="merge"]').onclick=()=>{wrap.remove();resolve({action:'merge',keep,remove})};wrap.querySelector('[data-a="different"]').onclick=()=>{wrap.remove();resolve({action:'different',keep,remove})};wrap.querySelector('[data-a="later"]').onclick=()=>{wrap.remove();resolve({action:'later'})}};draw();document.body.appendChild(wrap)})}
async function merge(keep,remove){const r=await fetch(MERGE_FN,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'merge',keep_id:Number(keep.id),remove_id:Number(remove.id)})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
async function run(){const banner=ensureBanner();if(!banner)return;try{const rows=await loadData(),pairs=candidatePairs(rows);if(!pairs.length){banner.style.display='none';return}banner.style.display='block';banner.innerHTML=`⚠ 似た材料が ${pairs.length}組あります<br><button type="button" style="margin-top:9px;width:100%;padding:11px;border:0;border-radius:10px;background:#b45309;color:#fff;font-weight:900">重複候補を確認する</button>`;banner.querySelector('button').onclick=async()=>{let current=candidatePairs(await loadData());while(current.length){const pair=current[0],ans=await ask(pair);if(ans.action==='later')break;if(ans.action==='different'){const s=ignored();s.add(pairKey(pair.a,pair.b));saveIgnored(s)}else if(ans.action==='merge'){try{await merge(ans.keep,ans.remove)}catch(e){alert('統合に失敗しました：'+e.message);break}}current=candidatePairs(await loadData())}await run();if(typeof loadAll==='function')loadAll().catch(()=>{});};}catch(e){console.error('duplicate review',e);banner.style.display='none'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,800),{once:true});else setTimeout(run,800);
})();