(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=2)=>{const v=Number(n)||0;return v.toLocaleString('ja-JP',{maximumFractionDigits:d})};
const yen=n=>Math.round(Number(n)||0).toLocaleString('ja-JP')+'円';
const today=()=>{const d=new Date(),z=d.getTimezoneOffset();return new Date(d.getTime()-z*60000).toISOString().slice(0,10)};
const DRAFT_KEY='material-stocktake-entry-v2';
let mats=[],moves=[],prices=[],entries=new Map();
function stockFor(id){const rows=moves.filter(x=>String(x.material_id)===String(id)).sort((a,b)=>(a.movement_date||'').localeCompare(b.movement_date||'')||Number(a.id)-Number(b.id));let s=0;for(const x of rows){const q=Number(x.quantity)||0;if(x.movement_type==='in')s+=q;else if(x.movement_type==='out')s-=q;else if(x.movement_type==='adjust')s=q}return s}
function latestPriceFor(id){return prices.filter(p=>String(p.material_id)===String(id)).sort((a,b)=>(b.effective_from||'').localeCompare(a.effective_from||'')||Number(b.id)-Number(a.id))[0]||null}
function unitValue(m,p){if(!p)return 0;if(p.price_basis==='kg'&&Number(m.unit_weight_kg)>0)return (Number(p.price)||0)*Number(m.unit_weight_kg);return Number(p.price)||0}
function materialLabel(m){return [m.supplier,m.name,m.spec,m.thickness_mm?`t${m.thickness_mm}`:'',m.color,m.purchase_form].filter(Boolean).join(' / ')}
async function load(){const [a,b,c]=await Promise.all([supabaseClient.from('materials').select('*').eq('active',true).order('supplier').order('name'),supabaseClient.from('inventory_movements').select('*').order('movement_date').order('id'),supabaseClient.from('material_prices').select('*').order('effective_from',{ascending:false})]);if(a.error||b.error||c.error)throw(a.error||b.error||c.error);mats=a.data||[];moves=b.data||[];prices=c.data||[]}
function loadDraft(){try{const x=JSON.parse(localStorage.getItem(DRAFT_KEY)||'{}');entries=new Map(Object.entries(x).filter(([id,q])=>mats.some(m=>String(m.id)===String(id))&&Number.isFinite(Number(q))).map(([id,q])=>[String(id),Number(q)]))}catch{entries=new Map()}}
function saveDraft(){try{localStorage.setItem(DRAFT_KEY,JSON.stringify(Object.fromEntries(entries)))}catch{}}
function init(){const tabs=document.querySelector('.material-tabs'),app=document.getElementById('materialApp');if(!tabs||!app)return;
let old=document.getElementById('mp-stocktake');if(old)old.remove();
const st=document.createElement('style');st.textContent=`
.stocktake-entry-card{border:1px solid #d8dee8;border-radius:14px;padding:14px;background:#fff;margin-bottom:12px}
.stocktake-entry-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.stocktake-entry-grid .full{grid-column:1/-1}
.stocktake-entry-grid label{display:block;font-size:12px;color:#64748b;font-weight:800;margin-bottom:5px}.stocktake-entry-grid select,.stocktake-entry-grid input{width:100%;box-sizing:border-box;padding:12px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;font-size:16px}
.stocktake-qty-wrap{display:grid;grid-template-columns:1fr auto;align-items:center;gap:8px}.stocktake-unit{font-size:18px;font-weight:900;min-width:35px}
.stocktake-add{width:100%;border:0;border-radius:12px;padding:14px;background:#262b31;color:#fff;font-weight:900;font-size:16px;margin-top:2px}
.stocktake-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.stocktake-summary-box{border:1px solid #d8dee8;border-radius:12px;padding:11px;background:#f8fafc}.stocktake-summary-box .l{font-size:11px;color:#64748b}.stocktake-summary-box .n{font-size:19px;font-weight:900;margin-top:3px}.stocktake-summary-box.total{grid-column:span 2}
.stocktake-list{display:grid;gap:9px}.stocktake-row{border:1px solid #d8dee8;border-radius:12px;padding:12px;background:#fff}.stocktake-row-top{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.stocktake-name{font-weight:900;font-size:15px;line-height:1.4}.stocktake-meta{font-size:11px;color:#64748b;margin-top:4px;line-height:1.5}.stocktake-actual{font-size:20px;font-weight:900;white-space:nowrap}.stocktake-money{font-size:13px;font-weight:800;margin-top:7px}.stocktake-diff{font-size:12px;font-weight:800;margin-top:4px}.stocktake-diff.same{color:#168447}.stocktake-diff.change{color:#b42318}.stocktake-row-actions{display:flex;gap:7px;margin-top:9px}.stocktake-row-actions button{border:1px solid #cbd5e1;background:#fff;border-radius:9px;padding:7px 11px;font-weight:800}.stocktake-row-actions .del{color:#b42318}
.stocktake-confirm{width:100%;border:0;border-radius:12px;padding:15px;background:#168447;color:#fff;font-weight:900;font-size:17px;margin-top:14px}.stocktake-reset{width:100%;border:1px solid #cbd5e1;border-radius:12px;padding:12px;background:#fff;color:#333;font-weight:800;font-size:14px;margin-top:8px}.stocktake-hint{font-size:12px;color:#64748b;line-height:1.6;margin:4px 0 10px}.stocktake-empty{padding:24px 8px;text-align:center;color:#64748b}.stocktake-progress{font-weight:900;margin:5px 0 12px}
@media(max-width:700px){.material-tabs{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:8px!important;overflow:visible!important}.material-tab{width:100%!important;min-width:0!important;padding:12px 6px!important;font-size:13px!important}.stocktake-entry-grid{grid-template-columns:1fr}.stocktake-entry-grid .full{grid-column:auto}.stocktake-summary{grid-template-columns:1fr 1fr}.stocktake-summary-box.total{grid-column:1/-1}}
`;document.head.appendChild(st);
let b=tabs.querySelector('.material-tab[data-tab="stocktake"]');if(!b){b=document.createElement('button');b.className='material-tab';b.dataset.tab='stocktake';b.textContent='棚卸し';tabs.appendChild(b)}
const s=document.createElement('section');s.className='material-panel';s.id='mp-stocktake';s.style.display='none';s.innerHTML=`<div class="card"><div class="card-title">棚卸し入力</div><div class="stocktake-hint">社員が数えてきた内容を、<b>仕入先 → 材料 → 数量</b>の順に入れるだけです。同じ材料をもう一度追加すると数量を足します。</div><div class="stocktake-entry-card"><div class="stocktake-entry-grid"><div><label>仕入先</label><select id="stSupplier"></select></div><div><label>材料</label><select id="stMaterial"></select></div><div class="full"><label>実際にあった数量</label><div class="stocktake-qty-wrap"><input id="stQty" type="number" step="any" inputmode="decimal" placeholder="例：25"><span id="stUnit" class="stocktake-unit"></span></div></div><div class="full"><button id="stAdd" class="stocktake-add">この材料を追加</button></div></div></div><div id="stocktakeSummary" class="stocktake-summary"></div><div id="stocktakeProgress" class="stocktake-progress"></div><div id="stocktakeList" class="stocktake-list"></div><button id="stocktakeConfirm" class="stocktake-confirm">入力した棚卸しを確定</button><button id="stocktakeReset" class="stocktake-reset">入力内容をすべてクリア</button></div>`;app.appendChild(s);
const supplier=s.querySelector('#stSupplier'),material=s.querySelector('#stMaterial'),qty=s.querySelector('#stQty'),unit=s.querySelector('#stUnit');
function suppliers(){return [...new Set(mats.map(m=>(m.supplier||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ja'))}
function renderSupplier(){supplier.innerHTML='<option value="">すべての仕入先</option>'+suppliers().map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
function filteredMaterials(){const v=supplier.value;return mats.filter(m=>!v||(m.supplier||'').trim()===v)}
function renderMaterial(){const list=filteredMaterials();material.innerHTML='<option value="">材料を選択してください</option>'+list.map(m=>`<option value="${m.id}">${esc([m.name,m.spec,m.thickness_mm?`t${m.thickness_mm}`:'',m.color,m.purchase_form].filter(Boolean).join(' / '))}</option>`).join('');unit.textContent=''}
function selectedMaterial(){return mats.find(m=>String(m.id)===String(material.value))}
function updateUnit(){const m=selectedMaterial();unit.textContent=m?.stock_unit||''}
function renderEntries(){let total=0,bookTotal=0,diffCount=0;const rows=[...entries.entries()].map(([id,q])=>{const m=mats.find(x=>String(x.id)===String(id));if(!m)return '';const book=stockFor(m.id),p=latestPriceFor(m.id),uv=unitValue(m,p),amount=Number(q)*uv,bookAmount=book*uv,diff=Number(q)-book;total+=amount;bookTotal+=bookAmount;if(Math.abs(diff)>=1e-9)diffCount++;return `<div class="stocktake-row" data-id="${m.id}"><div class="stocktake-row-top"><div><div class="stocktake-name">${esc(m.name)}</div><div class="stocktake-meta">${esc([m.supplier,m.spec,m.thickness_mm?`t${m.thickness_mm}`:'',m.color,m.purchase_form].filter(Boolean).join(' / '))}</div></div><div class="stocktake-actual">${fmt(q)} ${esc(m.stock_unit||'')}</div></div><div class="stocktake-money">棚卸金額 ${uv?yen(amount):'単価未登録'}${uv?`（単価 ${yen(uv)} / ${esc(m.stock_unit||'')}）`:''}</div><div class="stocktake-diff ${Math.abs(diff)<1e-9?'same':'change'}">帳簿 ${fmt(book)} ${esc(m.stock_unit||'')} → ${Math.abs(diff)<1e-9?'一致':`差異 ${diff>0?'+':''}${fmt(diff)} ${esc(m.stock_unit||'')}`}</div><div class="stocktake-row-actions"><button class="edit" data-id="${m.id}">数量を修正</button><button class="del" data-id="${m.id}">削除</button></div></div>`}).filter(Boolean);
s.querySelector('#stocktakeList').innerHTML=rows.length?rows.join(''):'<div class="stocktake-empty">まだ入力されていません。上で材料と数量を入れてください。</div>';
s.querySelector('#stocktakeSummary').innerHTML=`<div class="stocktake-summary-box"><div class="l">入力済み材料</div><div class="n">${entries.size} / ${mats.length}</div></div><div class="stocktake-summary-box"><div class="l">差異あり</div><div class="n">${diffCount}</div></div><div class="stocktake-summary-box total"><div class="l">入力済みの棚卸金額 合計</div><div class="n">${yen(total)}</div></div><div class="stocktake-summary-box"><div class="l">帳簿金額との差</div><div class="n">${(total-bookTotal)>=0?'+':''}${yen(total-bookTotal)}</div></div>`;
s.querySelector('#stocktakeProgress').textContent=entries.size===mats.length?'全材料の入力が完了しています。':`未入力 ${Math.max(0,mats.length-entries.size)}材料 ※未入力の材料は確定しても変更しません`;
s.querySelectorAll('.stocktake-row-actions .del').forEach(x=>x.onclick=()=>{entries.delete(String(x.dataset.id));saveDraft();renderEntries()});
s.querySelectorAll('.stocktake-row-actions .edit').forEach(x=>x.onclick=()=>{const m=mats.find(y=>String(y.id)===String(x.dataset.id));if(!m)return;supplier.value=(m.supplier||'').trim();renderMaterial();material.value=String(m.id);updateUnit();qty.value=entries.get(String(m.id));qty.focus();s.scrollIntoView({behavior:'smooth',block:'start'})});
}
async function show(){document.querySelectorAll('.material-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.material-panel').forEach(x=>{x.classList.remove('active');x.style.display='none'});b.classList.add('active');s.classList.add('active');s.style.display='block';await load();loadDraft();renderSupplier();renderMaterial();renderEntries();window.scrollTo({top:s.offsetTop-8,behavior:'auto'})}
b.onclick=e=>{e.preventDefault();e.stopPropagation();show().catch(er=>{console.error(er);alert('棚卸しデータの読み込みに失敗しました')})};
[...tabs.querySelectorAll('.material-tab')].filter(x=>x!==b).forEach(x=>x.addEventListener('click',()=>{s.style.display='none';s.classList.remove('active')}));
supplier.onchange=renderMaterial;material.onchange=updateUnit;
s.querySelector('#stAdd').onclick=()=>{const m=selectedMaterial(),q=Number(qty.value);if(!m){alert('材料を選択してください');return}if(qty.value===''||!Number.isFinite(q)||q<0){alert('数量を0以上の数字で入力してください');return}const id=String(m.id),old=entries.get(id);if(old!==undefined){if(!confirm(`${m.name} はすでに ${fmt(old)} ${m.stock_unit||''} 入っています。\n今回の ${fmt(q)} ${m.stock_unit||''} を足して ${fmt(old+q)} ${m.stock_unit||''} にしますか？`))return;entries.set(id,old+q)}else entries.set(id,q);saveDraft();renderEntries();qty.value='';qty.focus()};
s.querySelector('#stocktakeReset').onclick=()=>{if(!entries.size)return;if(!confirm('入力中の棚卸し内容をすべて消しますか？'))return;entries.clear();saveDraft();renderEntries()};
s.querySelector('#stocktakeConfirm').onclick=async()=>{if(!entries.size){alert('棚卸し数量を1件以上入力してください');return}let total=0;for(const [id,q] of entries){const m=mats.find(x=>String(x.id)===String(id));if(m)total+=Number(q)*unitValue(m,latestPriceFor(m.id))}if(!confirm(`棚卸しを確定します。\n入力済み ${entries.size}材料\n棚卸金額 ${yen(total)}\n\n未入力の材料は在庫を変更しません。`))return;const adjustments=[];for(const [id,actual] of entries){const m=mats.find(x=>String(x.id)===String(id));if(!m)continue;const book=stockFor(m.id);if(Math.abs(Number(actual)-book)>=1e-9)adjustments.push({material_id:Number(m.id),movement_date:today(),movement_type:'adjust',quantity:Number(actual),destination:'棚卸し',memo:`棚卸調整 帳簿:${book} → 実在庫:${actual}`,created_by:'factory@local'})}const btn=s.querySelector('#stocktakeConfirm');btn.disabled=true;btn.textContent='確定中…';try{if(adjustments.length){const {error}=await supabaseClient.from('inventory_movements').insert(adjustments);if(error)throw error}entries.clear();saveDraft();await load();renderEntries();if(typeof loadAll==='function')await loadAll();alert(`棚卸しを確定しました。\n入力 ${adjustments.length?entries.size:0}件のうち、差異 ${adjustments.length}件を在庫へ反映しました。`)}catch(er){console.error(er);alert('棚卸しの確定に失敗しました')}finally{btn.disabled=false;btn.textContent='入力した棚卸しを確定'}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();