(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>(Number(n)||0).toLocaleString('ja-JP');
const today=()=>{const d=new Date(),z=d.getTimezoneOffset();return new Date(d.getTime()-z*60000).toISOString().slice(0,10)};
let mats=[],moves=[];
function stockFor(id){const rows=moves.filter(x=>String(x.material_id)===String(id)).sort((a,b)=>(a.movement_date||'').localeCompare(b.movement_date||'')||Number(a.id)-Number(b.id));let s=0;for(const x of rows){const q=Number(x.quantity)||0;if(x.movement_type==='in')s+=q;else if(x.movement_type==='out')s-=q;else if(x.movement_type==='adjust')s=q}return s}
async function load(){const [a,b]=await Promise.all([supabaseClient.from('materials').select('*').eq('active',true).order('storage_location').order('name'),supabaseClient.from('inventory_movements').select('*').order('movement_date').order('id')]);if(a.error||b.error)throw(a.error||b.error);mats=a.data||[];moves=b.data||[]}
function init(){const tabs=document.querySelector('.material-tabs'),app=document.getElementById('materialApp');if(!tabs||!app||document.getElementById('mp-stocktake'))return;
const st=document.createElement('style');st.textContent=`@media(max-width:700px){.material-tabs{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:8px!important;overflow:visible!important}.material-tab{width:100%!important;min-width:0!important;padding:12px 6px!important;font-size:13px!important}.material-tab:last-child{grid-column:auto!important}}.stocktake-list{display:grid;gap:10px}.stocktake-row{border:1px solid #d8dee8;border-radius:12px;padding:12px;background:#fff}.stocktake-name{font-weight:900;font-size:16px}.stocktake-meta{font-size:12px;color:#64748b;margin-top:3px;line-height:1.5}.stocktake-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.stocktake-grid label{font-size:11px;color:#64748b}.stocktake-grid input{width:100%;box-sizing:border-box;padding:11px;border:1px solid #cbd5e1;border-radius:9px;font-size:17px}.stocktake-diff{margin-top:8px;font-weight:900}.stocktake-same{color:#168447}.stocktake-diffplus,.stocktake-diffminus{color:#b42318}.stocktake-summary{background:#f8fafc;border:1px solid #d8dee8;border-radius:12px;padding:12px;margin-bottom:12px}.stocktake-confirm{width:100%;border:0;border-radius:12px;padding:14px;background:#168447;color:#fff;font-weight:900;font-size:16px;margin-top:14px}.stocktake-unchecked{background:#fff7ed!important}`;document.head.appendChild(st);
const b=document.createElement('button');b.className='material-tab';b.dataset.tab='stocktake';b.textContent='棚卸し';tabs.appendChild(b);
const s=document.createElement('section');s.className='material-panel';s.id='mp-stocktake';s.style.display='none';s.innerHTML=`<div class="card"><div class="card-title">棚卸し</div><div class="material-note" style="margin-bottom:10px">実際にある数量を入力してください。差異だけ棚卸調整として履歴に残します。</div><div id="stocktakeSummary" class="stocktake-summary"></div><div id="stocktakeList" class="stocktake-list"></div><button id="stocktakeConfirm" class="stocktake-confirm">棚卸しを確定</button></div>`;app.appendChild(s);
async function show(){document.querySelectorAll('.material-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.material-panel').forEach(x=>{x.classList.remove('active');x.style.display='none'});b.classList.add('active');s.classList.add('active');s.style.display='block';await load();render();window.scrollTo({top:s.offsetTop-8,behavior:'auto'})}
b.onclick=e=>{e.preventDefault();e.stopPropagation();show().catch(er=>{console.error(er);alert('棚卸しデータの読み込みに失敗しました')})};
[...tabs.querySelectorAll('.material-tab')].filter(x=>x!==b).forEach(x=>x.addEventListener('click',()=>{s.style.display='none';s.classList.remove('active')}));
function render(){const list=s.querySelector('#stocktakeList');list.innerHTML=mats.map(m=>{const book=stockFor(m.id);return `<div class="stocktake-row" data-id="${m.id}" data-book="${book}"><div class="stocktake-name">${esc(m.name)}</div><div class="stocktake-meta">${esc([m.storage_location,m.category,m.spec,m.purchase_form].filter(Boolean).join(' / '))}</div><div class="stocktake-grid"><div><label>帳簿在庫</label><div style="font-weight:900;font-size:18px;padding:10px 0">${fmt(book)} ${esc(m.stock_unit||'')}</div></div><div><label>実在庫</label><input type="number" step="any" inputmode="decimal" placeholder="入力" data-unit="${esc(m.stock_unit||'')}"></div></div><div class="stocktake-diff">未確認</div></div>`}).join('')||'<div class="empty-state">材料がありません</div>';list.querySelectorAll('input').forEach(inp=>inp.addEventListener('input',update));update()}
function update(){let checked=0,diff=0,same=0;document.querySelectorAll('#stocktakeList .stocktake-row').forEach(row=>{const inp=row.querySelector('input'),out=row.querySelector('.stocktake-diff'),book=Number(row.dataset.book)||0;if(inp.value===''){out.textContent='未確認';out.className='stocktake-diff';row.classList.add('stocktake-unchecked');return}row.classList.remove('stocktake-unchecked');checked++;const actual=Number(inp.value);const d=actual-book;if(Math.abs(d)<1e-9){same++;out.textContent='一致';out.className='stocktake-diff stocktake-same'}else{diff++;out.textContent=`差異 ${d>0?'+':''}${fmt(d)} ${inp.dataset.unit}`;out.className='stocktake-diff '+(d>0?'stocktake-diffplus':'stocktake-diffminus')}});s.querySelector('#stocktakeSummary').innerHTML=`確認済み <b>${checked}</b> / ${mats.length}　 一致 <b>${same}</b>　 差異あり <b>${diff}</b>　 未確認 <b>${mats.length-checked}</b>`}
s.querySelector('#stocktakeConfirm').onclick=async()=>{const rows=[...s.querySelectorAll('.stocktake-row')],unchecked=rows.filter(r=>r.querySelector('input').value==='');if(unchecked.length){alert(`未確認が${unchecked.length}件あります。全部入力してから確定してください。`);unchecked[0].scrollIntoView({behavior:'smooth',block:'center'});return}const adjustments=[];for(const row of rows){const id=Number(row.dataset.id),book=Number(row.dataset.book)||0,actual=Number(row.querySelector('input').value);if(Math.abs(actual-book)>=1e-9)adjustments.push({material_id:id,movement_date:today(),movement_type:'adjust',quantity:actual,destination:'棚卸し',memo:`棚卸調整 帳簿:${book} → 実在庫:${actual}`,created_by:'factory@local'})}if(!confirm(`棚卸しを確定します。\n差異あり ${adjustments.length}件を在庫へ反映します。`))return;const btn=s.querySelector('#stocktakeConfirm');btn.disabled=true;btn.textContent='確定中…';try{if(adjustments.length){const {error}=await supabaseClient.from('inventory_movements').insert(adjustments);if(error)throw error}await load();render();if(typeof loadAll==='function')await loadAll();alert(`棚卸しを確定しました。差異 ${adjustments.length}件を反映しました。`)}catch(er){console.error(er);alert('棚卸しの確定に失敗しました')}finally{btn.disabled=false;btn.textContent='棚卸しを確定'}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();