(()=>{
'use strict';
const norm=s=>String(s||'').normalize('NFKC').replace(/[\s　]+/g,'').toLowerCase();
const displayName=s=>String(s||'').normalize('NFKC').replace(/[\s　]+/g,' ').trim();
const corporateFree=s=>displayName(s).replace(/[（(]\s*(?:株|有)\s*[）)]/g,'').replace(/株式会社|有限会社|合同会社|合資会社|合名会社/g,'').replace(/[\s　]+/g,' ').trim();
const companyGroup=s=>{const t=corporateFree(s);if(/^コタベ(?:\s|$)/.test(t))return{key:'コタベ',label:'コタベ'};if(/^リンテック(?:\s|$)/.test(t))return{key:'リンテック',label:'リンテック'};return null};
const shortSupplierName=s=>companyGroup(s)?.label||corporateFree(s);
const supplierKey=s=>{const grouped=companyGroup(s);if(grouped)return grouped.key;let t=String(s||'').normalize('NFKC').toLowerCase();t=t.replace(/[（(]\s*(?:株|有)\s*[）)]/g,'');t=t.replace(/株式会社|有限会社|合同会社|合資会社|合名会社/g,'');t=t.replace(/[\s　・･.．,，、\-‐‑–—_]/g,'');t=t.replace(/(?:本社|本店)$/,'');if(t.length>2)t=t.replace(/社$/,'');return t;};
let suppliers=[],refreshing=false,refreshTimer=null,sanitizing=false;
function sanitizeSupplierOptions(){const filter=document.getElementById('mSupplierFilter');if(!filter||sanitizing)return;sanitizing=true;try{const current=filter.value,seen=new Set(),keep=[];for(const o of [...filter.options]){if(!o.value){if(!seen.has('__all__')){seen.add('__all__');keep.push({value:'',text:'すべてのサプライヤー'})}continue}const original=displayName(o.dataset.fullName||o.textContent||o.label||''),key=supplierKey(original)||norm(original)||String(o.value);if(seen.has(key))continue;seen.add(key);keep.push({value:key,text:shortSupplierName(original),full:original})}filter.innerHTML='';for(const item of keep){const o=document.createElement('option');o.value=item.value;o.textContent=item.text;o.dataset.fullName=item.full;filter.appendChild(o)}if([...filter.options].some(o=>o.value===current))filter.value=current}finally{sanitizing=false}}
function installSupplierOptionGuard(){const filter=document.getElementById('mSupplierFilter');if(!filter)return false;if(filter.dataset.hardDedupeGuard==='1')return true;filter.dataset.hardDedupeGuard='1';let timer=null;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(sanitizeSupplierOptions,0)}).observe(filter,{childList:true});sanitizeSupplierOptions();return true}
function installLargeFileUploadFix(){if(window.__deliveryLargeUploadFixed)return;window.__deliveryLargeUploadFixed=true;const originalFetch=window.fetch.bind(window),target='https://vnnvuxccazkdzwqjmntz.supabase.co/functions/v1/delivery-note-ai',signer='https://vnnvuxccazkdzwqjmntz.supabase.co/functions/v1/delivery-upload-url';window.fetch=async function(input,init){const url=typeof input==='string'?input:(input?.url||'');if(url===target&&init?.method==='POST'&&typeof init.body==='string'){let body=null;try{body=JSON.parse(init.body)}catch{}if(body?.action==='store_source'&&body.base64){try{const metaRes=await originalFetch(signer,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({file_name:body.file_name,mime_type:body.mime_type,size:Math.floor((body.base64.length*3)/4)})}),meta=await metaRes.json();if(!metaRes.ok)throw new Error(meta.error||`HTTP ${metaRes.status}`);const bin=atob(body.base64),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);const blob=new Blob([bytes],{type:body.mime_type||'application/octet-stream'}),{error}=await supabaseClient.storage.from('delivery-notes').uploadToSignedUrl(meta.path,meta.token,blob,{contentType:body.mime_type||'application/octet-stream'});if(error)throw error;return new Response(JSON.stringify({ok:true,storage_path:meta.path}),{status:200,headers:{'Content-Type':'application/json'}})}catch(e){return new Response(JSON.stringify({error:'原本保存エラー: '+(e?.message||String(e))}),{status:500,headers:{'Content-Type':'application/json'}})}}}return originalFetch(input,init)}}
function getReviewItems(){const results=document.getElementById('deliveryResults');if(!results)return [];return [...results.querySelectorAll('.delivery-result')].filter(x=>x.dataset.safe!=='1'||x.classList.contains('uncertain')||x.querySelector('.delivery-warnings'))}
function jumpToFirstReview(){const first=getReviewItems()[0];if(!first)return false;first.scrollIntoView({behavior:'smooth',block:'center'});first.style.outline='4px solid #f59e0b';first.style.outlineOffset='4px';setTimeout(()=>{first.style.outline='';first.style.outlineOffset=''},1800);return true}
function fixReviewSummary(){const uncertain=getReviewItems();document.querySelectorAll('#deliveryReviewSummary').forEach(review=>{if(!uncertain.length){review.style.display='none';return}review.style.display='';const btn=review.querySelector('#jumpReview')||[...review.querySelectorAll('button')].find(b=>(b.textContent||'').includes('最初の要確認'));if(btn){btn.disabled=false;btn.style.pointerEvents='auto';btn.onclick=e=>{e.preventDefault();e.stopPropagation();jumpToFirstReview()}}})}
function installReviewJumpDelegation(){if(window.__deliveryReviewJumpDelegated)return;window.__deliveryReviewJumpDelegated=true;document.addEventListener('click',e=>{const btn=e.target.closest?.('button');if(!btn)return;if((btn.textContent||'').includes('最初の要確認')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();jumpToFirstReview()}},true)}
function watchReviewSummary(){const results=document.getElementById('deliveryResults');if(!results){setTimeout(watchReviewSummary,250);return}if(results.dataset.reviewObserver==='1')return;results.dataset.reviewObserver='1';let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(fixReviewSummary,50)}).observe(results,{childList:true,attributes:true,attributeFilter:['class'],subtree:true})}
async function loadSuppliers(){try{const {data,error}=await supabaseClient.from('materials').select('supplier').eq('active',true);if(error)throw error;const groups=new Map();for(const row of data||[]){const raw=displayName(row.supplier);if(!raw)continue;const key=supplierKey(raw)||norm(raw);if(!key)continue;if(!groups.has(key))groups.set(key,{key,label:companyGroup(raw)?.label||raw,count:0});const g=groups.get(key);g.count++;if(!companyGroup(raw)&&raw.length<g.label.length)g.label=raw}suppliers=[...groups.values()].sort((a,b)=>shortSupplierName(a.label).localeCompare(shortSupplierName(b.label),'ja'));renderChoices()}catch(e){console.error('supplier filter load',e)}}
function renderChoices(){const filter=document.getElementById('mSupplierFilter');if(!filter)return;const current=filter.value;filter.innerHTML='';const all=document.createElement('option');all.value='';all.textContent='すべてのサプライヤー';filter.appendChild(all);const used=new Set();for(const x of suppliers){const key=supplierKey(x.label)||x.key;if(!key||used.has(key))continue;used.add(key);const o=document.createElement('option');o.value=key;o.textContent=shortSupplierName(x.label);o.dataset.fullName=x.label;filter.appendChild(o)}sanitizeSupplierOptions();if([...filter.options].some(o=>o.value===current))filter.value=current;const dl=document.getElementById('mSupplierList');if(dl){dl.innerHTML='';const seen=new Set();for(const x of suppliers){const key=supplierKey(x.label)||x.key;if(!key||seen.has(key))continue;seen.add(key);const o=document.createElement('option');o.value=shortSupplierName(x.label);dl.appendChild(o)}}}
function applyFilter(){const filter=document.getElementById('mSupplierFilter');if(!filter)return;const key=filter.value;document.querySelectorAll('#mList .material-list-item').forEach(row=>{if(!key){row.style.display='';return}const meta=row.querySelector('.material-meta')?.innerText||'',rowKey=supplierKey(meta),normalizedMeta=norm(meta);row.style.display=(rowKey===key||rowKey.includes(key)||normalizedMeta.includes(norm(key)))?'':'none'})}
async function refreshInventory(){if(refreshing)return;refreshing=true;try{if(typeof loadAll==='function')await loadAll();await loadSuppliers();requestAnimationFrame(applyFilter)}catch(e){console.error('inventory live refresh',e)}finally{refreshing=false}}
function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refreshInventory,120)}
function watchDelivery(){const results=document.getElementById('deliveryResults');if(!results){setTimeout(watchDelivery,250);return}if(results.dataset.liveRefreshWatch)return;results.dataset.liveRefreshWatch='1';let doneCount=results.querySelectorAll('.delivery-result.delivery-done').length;new MutationObserver(()=>{const next=results.querySelectorAll('.delivery-result.delivery-done').length;if(next>doneCount)scheduleRefresh();doneCount=next}).observe(results,{subtree:true,childList:true,attributes:true,attributeFilter:['class']})}
function loadScriptOnce(src,key){if(window[key])return;window[key]=true;const s=document.createElement('script');s.src=src;document.body.appendChild(s)}
function hook(){installLargeFileUploadFix();installReviewJumpDelegation();watchReviewSummary();loadScriptOnce('./materials-edit.js?v=20260824-0407','__materialsEditLatest0407');loadScriptOnce('./delivery-normalize.js?v=20260823-2145','__deliveryNormalizerLoading');loadScriptOnce('./inventory-m2-display.js?v=20260823-2245','__inventoryM2DisplayLoading');loadScriptOnce('./lintec-label-explain.js?v=20260824-1507','__lintecLabelExplainLoading1507');loadScriptOnce('./lintec-m2-display.js?v=20260824-0407','__lintecM2Display0407');loadScriptOnce('./material-source-link.js?v=20260824-1529','__materialSourceLink1529');loadScriptOnce('./supplier-duplicate-review.js?v=20260823-2145','__supplierDuplicateReviewLoading');const filter=document.getElementById('mSupplierFilter');if(!filter){setTimeout(hook,200);return}installSupplierOptionGuard();if(!filter.dataset.directSupplierFix){filter.dataset.directSupplierFix='1';filter.addEventListener('change',applyFilter)}loadSuppliers();watchDelivery();const list=document.getElementById('mList');if(list&&!list.dataset.supplierFilterLight){list.dataset.supplierFilterLight='1';let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(applyFilter,30)}).observe(list,{childList:true})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook,{once:true});else hook();
})();